name: Fast Preprod Scan
on:
  workflow_dispatch:

jobs:
  build-and-test:
    name: Fast Scan
    runs-on: ubuntu-20.04
    services:
      vulny-node-express:
        image: bwvolleyball/demo_vuln_node
        ports:
          - 3000:3000
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Hawk CLI
        uses: stackhawk/hawkscan-action@v2
        with:
          installCLIOnly: true
      - name: Run CLI Scan
        env:
          APP_ID: ${{ secrets.HAWK_APP_ID }}
          COMMIT_SHA: ${{ github.sha }}
          BRANCH_NAME: ${{ github.head_ref }}
        run: hawk ${{ secrets.HAWK_TEST_OPTIONS }} --api-key=${{ secrets.HAWK_API_KEY }} scan
